name: CosmeticMenu
main: NinjaKnights\CosmeticMenu\Main
version: 2.3
api: 3.0.0
mcpe-protocol: [361, 388, 389, 390, 407, 408, 419]
author: TheKnightGamer / Jean
description: A CosmeticMenu plugin for server lobbys!
    
commands:
  cosmetics:
    description: "CosmeticMenu Command"

permissions:
  cosmeticmenu.all:
    default: op
    description: Permission for all CosmeticMenu features
    children:
      cosmeticmenu.item:
        description: Permission to access through the item
        default: op
      cosmeticmenu.cmd:
        description: Open the Cosmetic Form 
        default: op
      cosmeticmenu.gadgets:
        default: op
      cosmeticmenu.particles:
        default: op
      cosmeticmenu.suits:
        default: op
      cosmeticmenu.hats:
        default: op
      cosmeticmenu.trails:
        default: op
      cosmeticmenu.morphs:
        default: op
      cosmeticmenu.gadgets.tntlauncher:
        default: op
      cosmeticmenu.gadgets.lightningstick:
        default: op
      cosmeticmenu.gadgets.leaper:
        default: op
      cosmeticmenu.particles.raincloud:
        default: op
      cosmeticmenu.particles.flamingring:
        default: op
      cosmeticmenu.particles.blizzardaura:
        default: op
      cosmeticmenu.particles.cupidslove:
        default: op
      cosmeticmenu.particles.bullethelix:
        default: op
      cosmeticmenu.particles.conduitaura:
        default: op
      cosmeticmenu.particles.witchcurse:
        default: op
      cosmeticmenu.particles.emeraldtwirl:
        default: op
      cosmeticmenu.suits.youtube:
        default: op
      cosmeticmenu.suits.frog:
        default: op
      cosmeticmenu.hats.tv:
        default: op
      cosmeticmenu.hats.melon:
        default: op
      cosmeticmenu.trails.flame:
        default: op
      cosmeticmenu.trails.snow:
        default: op
      cosmeticmenu.trails.heart:
        default: op
      cosmeticmenu.trails.smoke:
        default: op
      cosmeticmenu.morphs.zombie:
        default: op